// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0iTHVLkmZejGNAYhbQXZHe6BG2KBOBK4',
    appId: '1:959574643326:web:8f79d096d9025ee3d67e2f',
    messagingSenderId: '959574643326',
    projectId: 'tugscode-1a450',
    authDomain: 'tugscode-1a450.firebaseapp.com',
    storageBucket: 'tugscode-1a450.appspot.com',
    measurementId: 'G-28LYTLWPFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvP3AnhzDlI7D3gyTmr_XtnCD83Mc9TWM',
    appId: '1:959574643326:android:142cc543512eebd3d67e2f',
    messagingSenderId: '959574643326',
    projectId: 'tugscode-1a450',
    storageBucket: 'tugscode-1a450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVKuOhSFi_0afcLafr5JOumBzZ8kOI03E',
    appId: '1:959574643326:ios:7aea6fac6ee9510fd67e2f',
    messagingSenderId: '959574643326',
    projectId: 'tugscode-1a450',
    storageBucket: 'tugscode-1a450.appspot.com',
    iosClientId: '959574643326-rnrnh5f0to4c8h8qqi5nv11dnetm5mto.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVKuOhSFi_0afcLafr5JOumBzZ8kOI03E',
    appId: '1:959574643326:ios:7aea6fac6ee9510fd67e2f',
    messagingSenderId: '959574643326',
    projectId: 'tugscode-1a450',
    storageBucket: 'tugscode-1a450.appspot.com',
    iosClientId: '959574643326-rnrnh5f0to4c8h8qqi5nv11dnetm5mto.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugs',
  );
}
